#! /bin/sh
### BEGIN INIT INFO
# Provides:		ruby
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Ruby app startup script
# Description:		Ruby app startup script
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/ruby
NAME=ruby
DESC=ruby

NAME=`basename ${0}`
EXEC=/usr/bin/ruby
ARGS="/opt/lamernews/app.rb -o 0.0.0.0"

case "$1" in
     start)
         echo "Starting $NAME ..."
         exec su - ruby -c "$EXEC $ARGS > /dev/null 2>&1 &"
         ;;
     stop)
         echo "Stopping $NAME ..."
         killall ruby
         ;;
     restart)
         echo "Restarting $NAME ..."
         $0 stop
         sleep 5
         $0 start
         ;;
     *)
         echo "Usage $0 {start|stop|restart}"
         ;;
esac
